//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGruData.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CodecAudio> CodecAudios { get; set; }
        public virtual DbSet<CodecVideo> CodecVideos { get; set; }
        public virtual DbSet<Contenedor> Contenedors { get; set; }
        public virtual DbSet<ContenedorCodecAudio> ContenedorCodecAudios { get; set; }
        public virtual DbSet<ContenedorCodecVideo> ContenedorCodecVideos { get; set; }
        public virtual DbSet<ContenedorTranscoder> ContenedorTranscoders { get; set; }
        public virtual DbSet<NodoConexion> NodoConexions { get; set; }
        public virtual DbSet<PuertoConexion> PuertoConexions { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trabajo> Trabajos { get; set; }
        public virtual DbSet<Transcoder> Transcoders { get; set; }
    }
}
