//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajo
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public string Resultado { get; set; }
        public string Comentarios { get; set; }
    }
}
