//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcoder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transcoder()
        {
            this.ContenedorTranscoders = new HashSet<ContenedorTranscoder>();
            this.NodoConexions = new HashSet<NodoConexion>();
        }
    
        public int IdTranscoder { get; set; }
        public string Nombre { get; set; }
        public string Version { get; set; }
        public string VersionAPI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenedorTranscoder> ContenedorTranscoders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NodoConexion> NodoConexions { get; set; }
    }
}
